name: CI

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Install
      run: |
        cd app
        npm install
        sed -e "s/%TOKEN%/${{ secrets.WD_TOKEN }}/g" \
            -e "s/%GUS_API_KEY%/${{ secrets.GUS_API_KEY }}/g" \
            config.template.js > config.js;
        cd ..
    - uses: ./.github/actions/hyperone-website-action
      with:
        token: "${{ secrets.HYPERONE_ACCESS_TOKEN_SECRET }}"
        website_id: "5d8d3f2393f2cc1f9a4015f3"
        website_password: "${{ secrets.WEBSITE_PASSWORD }}"
        destination: "./app/"
        source: "./app/"